import os

sample_names = []
sample_names.append('Powheg_qq_semilep_TT')
sample_names.append('Powheg_qq_semilep_TT_SC')
sample_names.append('Powheg_qq_semilep_TT_Mtt_700_to_1000')
sample_names.append('Powheg_qq_semilep_TT_Mtt_1000_to_Inf')
sample_names.append('Powheg_gg_semilep_TT')
sample_names.append('Powheg_gg_semilep_TT_SC')
sample_names.append('Powheg_gg_semilep_TT_Mtt_700_to_1000')
sample_names.append('Powheg_gg_semilep_TT_Mtt_1000_to_Inf')
sample_names.append('Powheg_dilep_TT')
sample_names.append('Powheg_dilep_TT_SC')
sample_names.append('Powheg_dilep_TT_Mtt_700_to_1000')
sample_names.append('Powheg_dilep_TT_Mtt_1000_to_Inf')
sample_names.append('Powheg_had_TT')
sample_names.append('Powheg_had_TT_SC')
sample_names.append('Powheg_had_TT_Mtt_700_to_1000')
sample_names.append('Powheg_had_TT_Mtt_1000_to_Inf')
sample_names.append('W1Jets')
sample_names.append('W2Jets')
sample_names.append('W3Jets')
sample_names.append('W4Jets')
sample_names.append('DY1Jets')
sample_names.append('DY2Jets')
sample_names.append('DY3Jets')
sample_names.append('DY4Jets')
sample_names.append('T_s')
sample_names.append('T_t')
sample_names.append('T_tW')
sample_names.append('Tbar_s')
sample_names.append('Tbar_t')
sample_names.append('Tbar_tW')
sample_names.append('SingleMu_Run2012A')
sample_names.append('SingleMu_Run2012B')
sample_names.append('SingleMu_Run2012C')
sample_names.append('SingleMu_Run2012D')
sample_names.append('SingleEl_Run2012A')
sample_names.append('SingleEl_Run2012B')
sample_names.append('SingleEl_Run2012C')
sample_names.append('SingleEl_Run2012D')

for name in sample_names :
    os.chdir(name)
    os.system('hadd '+name+'_all.root '+name+'*tree.root')
    os.system('mv *_all.root ../total_ttree_files')
    os.chdir('..')
    os.chdir(name+'_sb')
    os.system('hadd '+name+'_sb_all.root '+name+'*tree.root')
    os.system('mv *_all.root ../total_ttree_files')
    os.chdir('..')
os.chdir('total_ttree_files')
os.system('hadd SingleMu_Run2012_all.root SingleMu_Run2012*_all.root')
cmd = 'hadd Powheg_semilep_TT_all.root Powheg_qq_semilep_TT_all.root'
cmd += ' Powheg_qq_semilep_TT_SC_all.root Powheg_gg_semilep_TT_all.root Powheg_gg_semilep_TT_SC_all.root'
os.system(cmd)
os.chdir('..')
